sudo: required
services:
  - docker

before_install:
  - docker build -t hluan/react-test -f ./client/Dockerfile.dev .

script:
  - docker run hluan/react-test npm test -- --coverage

after_success:
  - docker build -t hluan/multi-client ./client
  - docker build -t hluan/multi-nginx ./nginx
  - docker build -t hluan/multi-server ./server
  - docker build -t hluan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push hluan/multi-client
  - docker push hluan/multi-nginx
  - docker push hluan/multi-server
  - docker push hluan/multi-worker

