sudo: required
services:
  - docker

before_install:
  - docker build -t hluandeloitte/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hluandeloitte/react-test npm test

after_success:
  - docker build -t hluandeloitte/multi-client ./client
  - docker build -t hluandeloitte/multi-nginx ./nginx
  - docker build -t hluandeloitte/multi-server ./server
  - docker build -t hluandeloitte/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # take those images and push them to docker hub
  - docker push hluandeloitte/multi-client
  - docker push hluandeloitte/multi-nginx
  - docker push hluandeloitte/multi-server
  - docker push hluandeloitte/multi-worker

